**EXERCISE 1:** Write a Python program that checks whether a number is positive or negative.

In [ ]:
num = float(input("Enter a number: "))
if num > 0:
   print("Number is a positive number.")
elif num < 0:
   print("Number is a negative number.")
else:
   print("Number is zero.")

Enter a number: -0.23
Number is a negative number.


**EXERCISE 2:** Declare variables of different data types and print their values.

In [ ]:
dataTypeInt = 100
print("Data Type is integar of", dataTypeInt)
dataTypeFloat = 12.98
print("Data Type is float of", dataTypeFloat)
dataTypeString = 'Zunaira Abdul Aziz'
print("Data Type is string of", dataTypeString)
dataTypeBoolean = True
print("Data Type is Boolean of", dataTypeBoolean)

Data Type is integar of 100
Data Type is float of 12.98
Data Type is string of Zunaira Abdul Aziz
Data Type is Boolean of True


**EXERCISE 3:** Write a program that checks whether a student has passed based on marks.

In [ ]:
marks = float(input("Enter marks of student to check if he passed or not: "))
if marks>=50:
  print("Student has passed his course.")
elif marks<50:
  print("Student has failed the course.")
else:
  print("Invalid marks.")

Enter marks of student to check if he passed or not: 21
Student has failed the course.


**EXERCISE 4:** Write a function that takes two numbers as input and returns their sum.

In [ ]:
num1 = float(input("Enter 1st number: "))
num2 = float(input("Enter 2nd number: "))
def sumOfTwoNumbers(num1, num2):
    totalSum = num1 + num2
    return totalSum
print("Sum of", num1, "and", num2, ":", sumOfTwoNumbers(num1, num2))

Enter 1st number: 12.23
Enter 2nd number: 23.90
Sum of 12.23 and 23.9 : 36.129999999999995


**EXERCISE 5:** Create a class named &#39;Car&#39; with attributes brand and year, and a method to display them.

In [ ]:
class Car:
  def __init__(self, brand, year, name, model):
    self.brand = brand
    self.year = year
    self.name = name
    self.model = model
  def display(self):
    print("Name:", self.name, ", Brand:", self.brand, ", Model:", self.model, ", Year:", self.year)

car1 = Car('Audi', 2019, 'A3 Audi', 'Q5')
car2 = Car('Toyata', 2020, 'Civics', '74')
print("Car 1")
car1.display()
print("Car 2")
car2.display()

Car 1
Name: A3 Audi , Brand: Audi , Model: Q5 , Year: 2019
Car 2
Name: Civics , Brand: Toyata , Model: 74 , Year: 2020


**EXERCISE 6:** Matrices

In [6]:
import numpy as np

print('Task 1 ')
matrix1 = np.array([[2, 3], [4, 5]])
Task1 = 2 * matrix1
print(Task1)

print('Task 2')
matrix2 = np.array([2, 3])
matrix3 = np.array([[4],[5]])
Task2 = np.dot(matrix2, matrix3)
print(Task2)

print('Task 3')
matrix4 = np.array([[1, 2], [3, 4]])
Task3 = np.dot(matrix2, matrix4)
print(Task3)

print('Task 4')
Task4 = matrix4.T
print(Task4)

print("Task 5")#get [1,2] and [3]
Task5Slice1 = matrix4[0, :]
Task5Slice2 = matrix4[1,0:1]
print(Task5Slice1)
print(Task5Slice2)

print("Task 6")
Task6 = np.linalg.inv(matrix4)
print(Task6)

Task 1 
[[ 4  6]
 [ 8 10]]
Task 2
[23]
Task 3
[11 16]
Task 4
[[1 3]
 [2 4]]
Task 5
[1 2]
[3]
Task 6
[[-2.   1. ]
 [ 1.5 -0.5]]


In [26]:
#VIVA QUESTION ASKED
m = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
m1 = m[:,:] #Selects all rows and all columns.
m2 = m[:,0] #Selects all rows but ONLY the 0th column.#Integer Indexing (Flattening)#Because you used a single number '0', NumPy "collapses" the dimension.
m3 = m[:,0:1] #Slice Indexing (Dimension Preservation): Selects all rows and columns from 0 to 1.# Because you used a slice '0:1', NumPy keeps the 2D structure.
m4 = m[1:3,0:1]#Selects rows 1 and 2 (index 3 is exclusive) and column 0.
print(m1)
print(m2)
print(m3)
print(m4)
print(m[2:3,0:3])
print(m[1:, 1:])
print(m[:, [0,2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[[1]
 [4]
 [7]]
[[4]
 [7]]
[[7 8 9]]
[[5 6]
 [8 9]]
[[1 3]
 [4 6]
 [7 9]]
